/* VOIDWORKS GIF//STUDIO · standalone GIF89a encoder · no third-party runtime */
'use strict';
let setup=null,items=[];
self.onmessage=e=>{const m=e.data;try{if(m.type==='start'){setup=m;items=[]}else if(m.type==='frame'){items.push({data:new Uint8Array(m.rgba),delay:m.delay})}else if(m.type==='encode'){if(!setup||items.length!==setup.count)throw Error('Frames were not received correctly');const buffer=encode();self.postMessage({type:'done',buffer},[buffer]);items=[]}}catch(err){self.postMessage({type:'error',message:String(err.message||err)})}};
function progress(value){self.postMessage({type:'progress',value})}
function uniformPalette(){const out=[];for(let r=0;r<8;r++)for(let g=0;g<8;g++)for(let b=0;b<4;b++)out.push([Math.round(r*255/7),Math.round(g*255/7),Math.round(b*255/3)]);return out}
function adaptivePalette(){const hist=new Uint32Array(32768),w=setup.width,h=setup.height;let samples=0;const stride=Math.max(1,Math.ceil(Math.sqrt(items.length*w*h/300000)));for(const f of items){const d=f.data;for(let y=0;y<h;y+=stride)for(let x=0;x<w;x+=stride){const i=(y*w+x)*4,k=((d[i]>>3)<<10)|((d[i+1]>>3)<<5)|(d[i+2]>>3);hist[k]++;samples++}}const entries=[];for(let k=0;k<32768;k++)if(hist[k])entries.push({r:((k>>10)&31)*8+4,g:((k>>5)&31)*8+4,b:(k&31)*8+4,n:hist[k]});if(!entries.length)return uniformPalette();const boxes=[{pts:entries}];function ranges(p){let r0=255,g0=255,b0=255,r1=0,g1=0,b1=0,count=0;for(const v of p){r0=Math.min(v.r,r0);g0=Math.min(v.g,g0);b0=Math.min(v.b,b0);r1=Math.max(v.r,r1);g1=Math.max(v.g,g1);b1=Math.max(v.b,b1);count+=v.n}return {r:r1-r0,g:g1-g0,b:b1-b0,count}}while(boxes.length<256){let best=-1,bestScore=-1,bestAxis='r';for(let i=0;i<boxes.length;i++){const p=boxes[i].pts;if(p.length<2)continue;const {r,g,b,count}=ranges(p),score=Math.max(r,g,b)*Math.sqrt(count);if(score>bestScore){best=i;bestScore=score;bestAxis=r>=g&&r>=b?'r':g>=b?'g':'b'}}if(best<0)break;const pts=boxes[best].pts;pts.sort((a,b)=>a[bestAxis]-b[bestAxis]);const total=pts.reduce((s,p)=>s+p.n,0);let mid=0,cum=0;while(mid<pts.length-1&&cum<total/2)cum+=pts[mid++].n;const left=pts.slice(0,mid),right=pts.slice(mid);if(!left.length||!right.length)break;boxes.splice(best,1,{pts:left},{pts:right})}const palette=boxes.map(box=>{let r=0,g=0,b=0,n=0;for(const p of box.pts){r+=p.r*p.n;g+=p.g*p.n;b+=p.b*p.n;n+=p.n}return [Math.min(255,Math.round(r/n)),Math.min(255,Math.round(g/n)),Math.min(255,Math.round(b/n))]});while(palette.length<256)palette.push([0,0,0]);return palette}
function buildLUT(palette,fast){const lut=new Uint8Array(32768);if(fast){for(let k=0;k<32768;k++){const r=(k>>10)&31,g=(k>>5)&31,b=k&31;lut[k]=((r>>2)<<5)|((g>>2)<<2)|(b>>3)}return lut}for(let key=0;key<32768;key++){const r=((key>>10)&31)*8+4,g=((key>>5)&31)*8+4,b=(key&31)*8+4;let best=0,score=Infinity;for(let i=0;i<palette.length;i++){const c=palette[i],dr=r-c[0],dg=g-c[1],db=b-c[2],d=2*dr*dr+3*dg*dg+db*db;if(d<score){score=d;best=i;if(score===0)break}}lut[key]=best}return lut}
function quantize(f,lut,pal,dither,w,h){const d=f.data,indices=new Uint8Array(w*h);if(!dither){for(let i=0,j=0;j<indices.length;j++,i+=4){const k=((d[i]>>3)<<10)|((d[i+1]>>3)<<5)|(d[i+2]>>3);indices[j]=lut[k]}return indices}let er=new Float32Array((w+2)*3),next=new Float32Array((w+2)*3);for(let y=0;y<h;y++){next.fill(0);for(let x=0;x<w;x++){const i=(y*w+x)*4,ei=(x+1)*3,r=Math.max(0,Math.min(255,d[i]+er[ei])),g=Math.max(0,Math.min(255,d[i+1]+er[ei+1])),b=Math.max(0,Math.min(255,d[i+2]+er[ei+2]));const key=((r>>3)<<10)|((g>>3)<<5)|(b>>3),idx=lut[key];indices[y*w+x]=idx;const c=pal[idx],dr=r-c[0],dg=g-c[1],db=b-c[2];for(let channel=0;channel<3;channel++){const v=channel===0?dr:channel===1?dg:db;er[ei+3+channel]+=v*7/16;next[ei-3+channel]+=v*3/16;next[ei+channel]+=v*5/16;next[ei+3+channel]+=v/16}}[er,next]=[next,er]}return indices}
function lzw(indices){const CLEAR=256,END=257,MAX=4096;const blocks=[];let current=[],bits=0,acc=0;function byte(b){current.push(b&255);if(current.length===255){blocks.push(current);current=[]}}function emit(code,size){acc|=code<<bits;bits+=size;while(bits>=8){byte(acc&255);acc>>>=8;bits-=8}}let table=new Map(),nextCode=258,size=9;function reset(){table=new Map();nextCode=258;size=9}emit(CLEAR,size);let prefix=indices[0];for(let i=1;i<indices.length;i++){const ch=indices[i],key=prefix*256+ch;if(table.has(key)){prefix=table.get(key)}else{emit(prefix,size);if(nextCode<MAX){table.set(key,nextCode++);if(nextCode>(1<<size)&&size<12)size++}else{emit(CLEAR,size);reset()}prefix=ch}}emit(prefix,size);emit(END,size);if(bits)byte(acc&255);if(current.length)blocks.push(current);return blocks}
function encode(){const {width:w,height:h,loop,quality,dither}=setup;if(w*h<1||w>1080||h>1080)throw Error('Invalid canvas dimensions');const pal=quality==='fast'?uniformPalette():adaptivePalette();progress(10);const lut=buildLUT(pal,quality==='fast');progress(17);const bytes=[];const put=(...v)=>bytes.push(...v),word=n=>put(n&255,(n>>8)&255),ascii=s=>{for(let i=0;i<s.length;i++)put(s.charCodeAt(i))};ascii('GIF89a');word(w);word(h);put(0xf7,0,0);for(const c of pal)put(...c); // 256-colour global palette
// NETSCAPE loop extension: 0 means forever, 1 means one iteration.
put(0x21,0xff,11);ascii('NETSCAPE2.0');put(3,1);word(loop);put(0);
for(let j=0;j<items.length;j++){const f=items[j];if(f.data.length!==w*h*4)throw Error('Frame size mismatch');const idx=quantize(f,lut,pal,dither,w,h);const delay=Math.max(2,Math.min(65535,Math.round(f.delay/10)));put(0x21,0xf9,4,0x08);word(delay);put(0,0);put(0x2c);word(0);word(0);word(w);word(h);put(0);put(8);const blocks=lzw(idx);for(const b of blocks){put(b.length);bytes.push(...b)}put(0);progress(Math.round((j+1)/items.length*100))}put(0x3b);const a=new Uint8Array(bytes);return a.buffer}
